[project]
name = "AutoClass3D"
channels = ["nvidia/label/cuda-11.8.0", "conda-forge", "bioconda", "nvidia", "pytorch"]
platforms = ["linux-64"]
authors = ["Han Zhu <zhu773@purdue.edu>"]
readme = "README.md"
repository = "https://github.itap.purdue.edu/kiharalab/AutoClass3D/"

[tasks]

[dependencies]
python = "3.11.*"
cuda = { version = "*", channel = "nvidia/label/cuda-11.8.0"}
pytorch = { version = "2.0.*", channel = "pytorch" }
pytorch-cuda = { version = "11.8.*", channel = "pytorch"}
scikit-learn = "*"
scikit-image = "*"
matplotlib = "*"
biopython = "*"
numba = "*"
numpy = "*"
scipy = "*"
tqdm = "*"
mrcfile = "*"
loguru = "*"

[pypi-dependencies]
ortools = ">=9.11.4210, <10"
progress = ">=1.6, <2"
numba-progress = ">=1.1.0, <2"
