# RELION optimiser; version 5.0-alpha-2-commit-f424a5
# --o InitialModel/job015/run --iter 100 --grad --denovo_3dref --i Select/job014/particles.star --ctf --K 1 --sym C1 --flatten_solvent --zero_mask --dont_combine_weights_via_disc --pool 3 --pad 1 --particle_diameter 200 --oversampling 1 --healpix_order 1 --offset_range 6 --offset_step 2 --auto_sampling --tau2_fudge 4 --j 12 --gpu 0,1,2,3 --pipeline_control InitialModel/job015/ 

# version 30001

data_optimiser_general

_rlnOutputRootName                                    InitialModel/job015/run
_rlnModelStarFile                                     InitialModel/job015/run_it100_model.star
_rlnExperimentalDataStarFile                          InitialModel/job015/run_it100_data.star
_rlnTomoTomogramsFile                                 ""
_rlnTomoTrajectoriesFile                              ""
_rlnOrientSamplingStarFile                            InitialModel/job015/run_it100_sampling.star
_rlnCurrentIteration                                           100
_rlnNumberOfIterations                                         100
_rlnDoSplitRandomHalves                                          0
_rlnJoinHalvesUntilThisResolution                         -1.00000
_rlnAdaptiveOversampleOrder                                      1
_rlnAdaptiveOversampleFraction                            0.999000
_rlnRandomSeed                                          1697712386
_rlnParticleDiameter                                    200.000000
_rlnWidthMaskEdge                                                5
_rlnDoZeroMask                                                   1
_rlnDoSolventFlattening                                          1
_rlnDoSolventFscCorrection                                       0
_rlnSolventMaskName                                   None
_rlnSolventMask2Name                                  None
_rlnBodyStarFile                                      None
_rlnTauSpectrumName                                   None
_rlnMaximumCoarseImageSize                                      -1
_rlnHighresLimitExpectation                               -1.00000
_rlnLowresLimitExpectation                                -1.00000
_rlnIncrementImageSize                                          10
_rlnDoMapEstimation                                              1
_rlnDoFastSubsetOptimisation                                     0
_rlnDoExternalReconstruct                                        0
_rlnDoGradientRefine                                             1
_rlnDoStochasticGradientDescent                                  1
_rlnGradEmIters                                                  0
_rlnGradHasConverged                                             0
_rlnGradCurrentStepsize                                   0.500000
_rlnGradSubsetOrder                                              0
_rlnGradSuspendFinerSamplingIter                                -1
_rlnGradSuspendLocalSamplingIter                                -1
_rlnSgdInitialIterationsFraction                          0.300000
_rlnSgdFinalIterationsFraction                            0.200000
_rlnSgdMinimumResolution                                 20.000000
_rlnSgdInitialResolution                                  -1.00000
_rlnSgdFinalResolution                                    -1.00000
_rlnSgdInitialSubsetSize                                       200
_rlnSgdFinalSubsetSize                                        1000
_rlnSgdMuFactor                                           0.900000
_rlnSgdSkipAnneal                                                0
_rlnSgdClassInactivityThreshold                           0.000000
_rlnSgdSubsetSize                                             1000
_rlnSgdWriteEverySubset                                         10
_rlnSgdStepsize                                           -1.00000
_rlnSgdStepsizeScheme                                 ""
_rlnTau2FudgeScheme                                   ""
_rlnTau2FudgeArg                                          4.000000
_rlnMaximumSignificantPoses                                     -1
_rlnDoAutoRefine                                                 0
_rlnDoAutoSampling                                               1
_rlnAutoLocalSearchesHealpixOrder                                4
_rlnNumberOfIterWithoutResolutionGain                            1
_rlnBestResolutionThusFar                                 0.128001
_rlnNumberOfIterWithoutChangingAssignments                       0
_rlnDoSkipAlign                                                  0
_rlnDoSkipRotate                                                 0
_rlnOverallAccuracyRotations                              1.391000
_rlnOverallAccuracyTranslationsAngst                      1.058460
_rlnChangesOptimalOrientations                           24.837475
_rlnChangesOptimalOffsets                                 0.680107
_rlnChangesOptimalClasses                                 0.000000
_rlnSmallestChangesOrientations                          24.837475
_rlnSmallestChangesOffsets                                0.680107
_rlnSmallestChangesClasses                                       0
_rlnLocalSymmetryFile                                 None
_rlnDoHelicalRefine                                              0
_rlnIgnoreHelicalSymmetry                                        0
_rlnFourierMask                                       None
_rlnHelicalTwistInitial                                   0.000000
_rlnHelicalRiseInitial                                    0.000000
_rlnHelicalCentralProportion                              0.300000
_rlnNrHelicalNStart                                              1
_rlnHelicalMaskTubeInnerDiameter                          -1.00000
_rlnHelicalMaskTubeOuterDiameter                          -1.00000
_rlnHelicalSymmetryLocalRefinement                               0
_rlnHelicalSigmaDistance                                  -1.00000
_rlnHelicalKeepTiltPriorFixed                                    0
_rlnHasConverged                                                 0
_rlnHasHighFscAtResolLimit                                       0
_rlnHasLargeSizeIncreaseIterationsAgo                            0
_rlnDoCorrectNorm                                                0
_rlnDoCorrectScale                                               0
_rlnDoCorrectCtf                                                 1
_rlnDoCenterClasses                                              0
_rlnDoIgnoreCtfUntilFirstPeak                                    0
_rlnCtfDataArePhaseFlipped                                       0
_rlnDoOnlyFlipCtfPhases                                          0
_rlnRefsAreCtfCorrected                                          1
_rlnFixSigmaNoiseEstimates                                       0
_rlnFixSigmaOffsetEstimates                                      0
_rlnMaxNumberOfPooledParticles                                  36
_rlnOffsetRangeX                                          -1.00000
_rlnOffsetRangeX                                          -1.00000
_rlnOffsetRangeX                                          -1.00000
 
