# RELION optimiser; version 5.0-alpha-2-commit-f424a5
# --o Class3D/job016/run --i Select/job014/particles.star --ref InitialModel/job015/initial_model.mrc --ini_high 50 --dont_combine_weights_via_disc --preread_images --pool 30 --pad 1 --ctf --iter 25 --tau2_fudge 4 --particle_diameter 200 --blush --K 4 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale --j 6 --gpu 0:1:2:3 --pipeline_control Class3D/job016/ 

# version 30001

data_optimiser_general

_rlnOutputRootName                                    Class3D/job016/run
_rlnModelStarFile                                     Class3D/job016/run_it025_model.star
_rlnExperimentalDataStarFile                          Class3D/job016/run_it025_data.star
_rlnTomoTomogramsFile                                 ""
_rlnTomoTrajectoriesFile                              ""
_rlnOrientSamplingStarFile                            Class3D/job016/run_it025_sampling.star
_rlnCurrentIteration                                            25
_rlnNumberOfIterations                                          25
_rlnDoSplitRandomHalves                                          0
_rlnJoinHalvesUntilThisResolution                         -1.00000
_rlnAdaptiveOversampleOrder                                      1
_rlnAdaptiveOversampleFraction                            0.999000
_rlnRandomSeed                                          1697715426
_rlnParticleDiameter                                    200.000000
_rlnWidthMaskEdge                                                5
_rlnDoZeroMask                                                   1
_rlnDoSolventFlattening                                          1
_rlnDoSolventFscCorrection                                       0
_rlnSolventMaskName                                   None
_rlnSolventMask2Name                                  None
_rlnBodyStarFile                                      None
_rlnTauSpectrumName                                   None
_rlnMaximumCoarseImageSize                                      -1
_rlnHighresLimitExpectation                               -1.00000
_rlnLowresLimitExpectation                                -1.00000
_rlnIncrementImageSize                                          10
_rlnDoMapEstimation                                              1
_rlnDoFastSubsetOptimisation                                     0
_rlnDoExternalReconstruct                                        0
_rlnDoGradientRefine                                             0
_rlnDoStochasticGradientDescent                                  0
_rlnGradEmIters                                                  0
_rlnGradHasConverged                                             0
_rlnGradCurrentStepsize                                   0.000000
_rlnGradSubsetOrder                                              0
_rlnGradSuspendFinerSamplingIter                                -1
_rlnGradSuspendLocalSamplingIter                                -1
_rlnSgdInitialIterationsFraction                          0.300000
_rlnSgdFinalIterationsFraction                            0.200000
_rlnSgdMinimumResolution                                 20.000000
_rlnSgdInitialResolution                                  -1.00000
_rlnSgdFinalResolution                                    -1.00000
_rlnSgdInitialSubsetSize                                        -1
_rlnSgdFinalSubsetSize                                          -1
_rlnSgdMuFactor                                           0.000000
_rlnSgdSkipAnneal                                                0
_rlnSgdClassInactivityThreshold                           0.000000
_rlnSgdSubsetSize                                               -1
_rlnSgdWriteEverySubset                                         10
_rlnSgdStepsize                                           -1.00000
_rlnSgdStepsizeScheme                                 ""
_rlnTau2FudgeScheme                                   ""
_rlnTau2FudgeArg                                          4.000000
_rlnMaximumSignificantPoses                                     -1
_rlnDoAutoRefine                                                 0
_rlnDoAutoSampling                                               0
_rlnAutoLocalSearchesHealpixOrder                                4
_rlnNumberOfIterWithoutResolutionGain                            7
_rlnBestResolutionThusFar                                 0.079449
_rlnNumberOfIterWithoutChangingAssignments                       9
_rlnDoSkipAlign                                                  0
_rlnDoSkipRotate                                                 0
_rlnOverallAccuracyRotations                              3.925000
_rlnOverallAccuracyTranslationsAngst                      2.361180
_rlnChangesOptimalOrientations                           76.597729
_rlnChangesOptimalOffsets                                 2.102866
_rlnChangesOptimalClasses                                 0.002175
_rlnSmallestChangesOrientations                          55.541380
_rlnSmallestChangesOffsets                                1.758451
_rlnSmallestChangesClasses                                       0
_rlnLocalSymmetryFile                                 None
_rlnDoHelicalRefine                                              0
_rlnIgnoreHelicalSymmetry                                        0
_rlnFourierMask                                       None
_rlnHelicalTwistInitial                                   0.000000
_rlnHelicalRiseInitial                                    0.000000
_rlnHelicalCentralProportion                              0.300000
_rlnNrHelicalNStart                                              1
_rlnHelicalMaskTubeInnerDiameter                          -1.00000
_rlnHelicalMaskTubeOuterDiameter                          -1.00000
_rlnHelicalSymmetryLocalRefinement                               0
_rlnHelicalSigmaDistance                                  -1.00000
_rlnHelicalKeepTiltPriorFixed                                    0
_rlnHasConverged                                                 0
_rlnHasHighFscAtResolLimit                                       0
_rlnHasLargeSizeIncreaseIterationsAgo                            0
_rlnDoCorrectNorm                                                1
_rlnDoCorrectScale                                               1
_rlnDoCorrectCtf                                                 1
_rlnDoCenterClasses                                              0
_rlnDoIgnoreCtfUntilFirstPeak                                    0
_rlnCtfDataArePhaseFlipped                                       0
_rlnDoOnlyFlipCtfPhases                                          0
_rlnRefsAreCtfCorrected                                          1
_rlnFixSigmaNoiseEstimates                                       0
_rlnFixSigmaOffsetEstimates                                      0
_rlnMaxNumberOfPooledParticles                                 180
_rlnOffsetRangeX                                          -1.00000
_rlnOffsetRangeX                                          -1.00000
_rlnOffsetRangeX                                          -1.00000
 
